### PR TITLE
fix(cli): traverse parent directories to find vite.config.ts in vp pack

### LINKED ISSUE #942: Bug: vp pack does not traverse upward to read pack configuration from vite.config.ts
### Describe the bug

When using tsdown, if tsdown.config.ts is configured in the project root, running the tsdown command inside a subpackage will traverse upward and read the configuration from the root directory.

However, when using vp pack in vite-plus, the command does not traverse parent directories to read configuration defined in vite.config.ts.

It would be helpful if vp pack could support similar behavior: when executed inside a subdirectory (such as a subpackage in a monorepo), it should traverse upward and load configuration from the nearest vite.config.ts, including the pack configuration.

This would make it easier to use vite-plus in monorepo setups where the shared configuration is defined at the repository root.

### Reproduction

null

### Steps to reproduce

_No response_

### System Info

```shell
vp pack
```

### Used Package Manager

pnpm

### Logs

```shell

```

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/voidzero-dev/vite-plus/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/voidzero-dev/vite-plus/issues) for the same bug.
- [x] Confirm this is a Vite+ issue and not an upstream issue (Vite, Vitest, tsdown, Rolldown, or Oxc).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

### PR DESCRIPTION
**Pull request by kazupon**
resolve #942

### CODE REVIEW

File: packages/cli/src/resolve-vite-config.ts [hunk 1]
```diff
@@ -1,8 +1,96 @@
+import fs from 'node:fs';
+import path from 'node:path';
+
+const VITE_CONFIG_FILES = [
+  'vite.config.js',
+  'vite.config.mjs',
+  'vite.config.ts',
```
Comment (fengmk2) [inline packages/cli/src/resolve-vite-config.ts]: In the vast majority of cases it's the `vite.config.ts` file, put it first so there will only be one file IO operation

File: packages/cli/snap-tests/command-pack-monorepo/snap.txt [hunk 2]
```diff
@@ -2,17 +2,48 @@
...
+ℹ entry: src/sub/index.ts
+ℹ Build start
+ℹ Cleaning 2 files
+ℹ dist/index.mjs    <variable> kB │ gzip: <variable> kB
+ℹ dist/index.d.mts  <variable> kB │ gzip: <variable> kB
+ℹ 2 files, total: <variable> kB
+✔ Build complete in <variable>ms
+
+---
+vp run: array-config#build not cached because it modified its input. (Run `vp run --last-details` for full details)
```
Comment (fengmk2) [inline packages/cli/snap-tests/command-pack-monorepo/snap.txt:33]:
```bash
> vp run --last-details

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    Vite+ Task Runner • Execution Summary
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Statistics:   1 tasks • 0 cache hits • 1 cache misses
Performance:  0% cache hit rate

Task Details:
────────────────────────────────────────────────
  [1] hello#build: ~/packages/hello$ vp pack ✓
      → Not cached: read and wrote 'packages/hello/dist/index.cjs'
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

> vp run --last-details

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    Vite+ Task Runner • Execution Summary
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Statistics:   1 tasks • 0 cache hits • 1 cache misses
Performance:  0% cache hit rate

Task Details:
────────────────────────────────────────────────
  [1] hello#build: ~/packages/hello$ vp pack ✓
      → Not cached: read and wrote 'node_modules/.vite-temp/vite.config.ts.timestamp-1774171302767-0e1b7c94f16fd.mjs'
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

Comment (fengmk2) [reply packages/cli/snap-tests/command-pack-monorepo/snap.txt:33]: follow up here https://github.com/voidzero-dev/vite-plus/issues/1095
