### PR TITLE
fix(test): include `aria-role.d.ts` in `@voidzero-dev/vite-plus-test` package

### LINKED ISSUE #908: `vp pack` fails with UNRESOLVED_IMPORT for `./aria-role.js` during dts bundling
### Describe the bug

When generating DTS bundles with `vp pack`, the build fails because `./aria-role.js` referenced in the `@voidzero-dev/vite-plus-test` package's type definitions cannot be resolved.

When importing the `UserConfig` type from `vite-plus` in the library source code, the DTS bundler follows the type dependency chain as follows:

1. `import type { UserConfig } from 'vite-plus'`
2. → `vite-plus/dist/index.d.ts`
3. → `@voidzero-dev/vite-plus-test/config.d.ts`
4. → `@voidzero-dev/vite-plus-test/dist/@vitest/browser/index.d.ts`
5. → `@voidzero-dev/vite-plus-test/dist/@vitest/browser/context.d.ts`
6. → `import { ARIARole } from './aria-role.js'` — **this file does not exist in the package**

Expected behavior: `vp pack` completes the build successfully and generates DTS files.
Actual behavior: The build fails with `[UNRESOLVED_IMPORT] Error: Could not resolve './aria-role.js'`.

### Reproduction

https://github.com/kazupon/vp-config/tree/repro-1

### Steps to reproduce

```sh
git clone https://github.com/kazupon/vp-config.git
cd vp-config
git checkout repro-1
vp install
vp pack
```

### System Info

```shell
vp v0.1.11

Local vite-plus:
  vite-plus  v0.1.11

Tools:
  vite             v8.0.0
  rolldown         v1.0.0-rc.9
  vitest           v4.1.0
  oxfmt            v0.40.0
  oxlint           v1.55.0
  oxlint-tsgolint  v0.16.0
  tsdown           v0.21.2

Environment:
  Node Version  24.14.0
  OS            Darwin 24.5.0
```

### Used Package Manager

pnpm

### Logs

```shell
ℹ entry: src/index.ts
ℹ tsconfig: tsconfig.json
ℹ Build start
The `tsgo` option is experimental and may change in the future.
(rolldown-plugin-dts:fake-js plugin) `declare module "../@vitest/expect/index.js"` will be kept as-is in the output.
(rolldown-plugin-dts:fake-js plugin) `declare module "../@vitest/runner/index.js"` will be kept as-is in the output.

error: Build failed with 1 error:

[UNRESOLVED_IMPORT] Error: Could not resolve './aria-role.js' in
  node_modules/.pnpm/@voidzero-dev+vite-plus-test@0.1.11_.../dist/@vitest/browser/context.d.ts

   3 │ import { ARIARole } from './aria-role.js';
     │                          ────────────────
     │                          Module not found.

Help: imported by the following path:
  - .../@voidzero-dev/vite-plus-test/dist/@vitest/browser/context.d.ts
  - .../@voidzero-dev/vite-plus-test/dist/@vitest/browser/index.d.ts
  - .../@voidzero-dev/vite-plus-test/dist/config.d.ts
  - .../@voidzero-dev/vite-plus-test/config.d.ts
  - .../vite-plus/dist/index.d.ts
  - src/format.d.ts
  - src/index.d.ts
```

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/voidzero-dev/vite-plus/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/voidzero-dev/vite-plus/issues) for the same bug.
- [x] Confirm this is a Vite+ issue and not an upstream issue (Vite, Vitest, tsdown, Rolldown, or Oxc).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

### PR DESCRIPTION
**Pull request by kazupon**
resolve #908

### CODE REVIEW

File: packages/test/build.ts [hunk 1]
```diff
@@ -611,8 +611,11 @@ async function copyVitestPackages() {
     console.log(`    -> ${copied} files`);
 
     // Copy root type definition files if they exist
-    // These include context.d.ts (browser providers), matchers.d.ts (expect.element), jest-dom.d.ts (matchers)
-    const rootDtsFiles = ['context.d.ts', 'matchers.d.ts', 'jest-dom.d.ts'];
+    // These include context.d.ts (browser providers), matchers.d.ts (expect.element),
+    // jest-dom.d.ts (matchers), aria-role.d.ts (ARIARole type used by context.d.ts)
+    // TODO: consider dynamically scanning root .d.ts files instead of hardcoding,
```
Comment (kazupon) [inline packages/test/build.ts:616]: As I mentioned in the comments under `TODO`, this PR only resolves the issue at hand, but fundamentally, we should dynamically scan and import the DTS provided by `@vitest/browser`.

Comment (fengmk2) [reply packages/test/build.ts:616]: yes, I see still missing https://npmx.dev/package-code/@vitest/browser/v/4.1.0/utils.d.ts too. Can fix in a future pr.
