### PR TITLE
fix: correctly resolve tsgolint in yarn monorepo packages

### LINKED ISSUE #1296: `vp check` fails in Yarn monorepo nested directory
### Describe the bug

Yarn monorepos do not create a `node_modules` under every package, unlike pnpm. When running `vp check` from any nested directory, it fails with:

```
error: Linting could not start
Failed to find tsgolint executable: OXLINT_TSGOLINT_PATH points to '.\node_modules\.bin\tsgolint.cmd' which does not exist
```

This works correctly for `pnpm` monorepos, as pnpm symlinks `node_modules` in every package.

### Steps to reproduce

1. Create a new Yarn monorepo, note this currently fails due to #1295, so setting `nodeLinker: node-modules` is necessary after running `vp create`
2. Run `vp check` - works
3. `cd packages/utils && vp check` - fails

### System Info

```shell
VITE+ - The Unified Toolchain for the Web

Environment:
  Version       24.4.0
  Source        engines.node

Tool Paths:
  node  C:\Users\Matei\.vite-plus\js_runtime\node\24.4.0\node.exe
  npm   C:\Users\Matei\.vite-plus\js_runtime\node\24.4.0\npm.cmd
  npx   C:\Users\Matei\.vite-plus\js_runtime\node\24.4.0\npx.cmd

Local vite-plus:
  vite-plus  v0.1.15

Tools:
  vite             v8.0.3
  rolldown         v1.0.0-rc.12
  vitest           v4.1.2
  oxfmt            v0.43.0
  oxlint           v1.58.0
  oxlint-tsgolint  v0.18.1
  tsdown           v0.21.7

Environment:
  Package manager  yarn v4.13.0
  Node.js          v24.4.0 (engines.node)
```

### Used Package Manager

yarn

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/voidzero-dev/vite-plus/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/voidzero-dev/vite-plus/issues) for the same bug.
- [x] Confirm this is a Vite+ issue and not an upstream issue (Vite, Vitest, tsdown, Rolldown, or Oxc).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

### PR DESCRIPTION
**Pull request by rChaoz**
Closes #1296

The `oxlint-tsgolint` executable resolution algorithm assumes that there is a `node_modules` directory in the current working directory (current package directory). However, this is only true for `pnpm`, `yarn` only creates a single `node_modules` in the workspace root, unlike `pnpm` which creates one under every package.

Because of this, `vp lint`/`vp check` fail to find the `tsgolint` executable. Updates the algorithm to extract the `node_modules` directory location based on `resolve()`, rather than `process.cwd()`.

Additionally improves the error message to list all tried paths, rather than just one:

**Before**
```
VITE+ - The Unified Toolchain for the Web

Failed to find tsgolint executable: OXLINT_TSGOLINT_PATH points to '.\node_modules\.bin\tsgolint.cmd' which does not exist
```

**Now**
```
VITE+ - The Unified Toolchain for the Web

error: Failed to resolve lint command: GenericFailure, Error: Unable to resolve oxlint-tsgolint executable, tried:
- C:\Users\Matei\projects\agent-lab\node_modules\vite-plus\node_modules\.bin\tsgolint.exe
- C:\Users\Matei\projects\agent-lab\node_modules\vite-plus\node_modules\.bin\tsgolint.cmd
- C:\Users\Matei\projects\agent-lab\node_modules\.bin\tsgolint.exe
- C:\Users\Matei\projects\agent-lab\node_modules\.bin\tsgolint.cmd
```

### CODE REVIEW

File: packages/cli/src/resolve-lint.ts [hunk 1]
```diff
@@ -67,7 +68,10 @@ export async function lint(): Promise<{
       }
     }
     if (!oxlintTsgolintPath) {
-      oxlintTsgolintPath = join(cwdBinDir, 'tsgolint.cmd');
```
Comment (rChaoz) [inline packages/cli/src/resolve-lint.ts:70]: Note: this default value was guaranteed not to exist as `existsSync()` returned `false` for it a few lines above
