### PR TITLE
fix: add troubleshooting tips for npm template not found error

### LINKED ISSUE #828: Incorrect registry causing project creation to fail
### Describe the bug

When I want to create a new Vite Plus using the `vp create <name>`, the CLI fetches from `https://registry.npmjs.org/<name>` which returns error 404.

` ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/create-vite-plus-app: Not Found - 404`

Image

### Reproduction

none

### Steps to reproduce

Run `vp create <name>`

### System Info

```shell
Environment:
  Version  24.14.0
  Source   lts

Tool Paths:
  node  /Users/azizbecha/.vite-plus/js_runtime/node/24.14.0/bin/node
  npm   /Users/azizbecha/.vite-plus/js_runtime/node/24.14.0/bin/npm
  npx   /Users/azizbecha/.vite-plus/js_runtime/node/24.14.0/bin/npx

vp v0.1.11

Local vite-plus:
  vite-plus  Not found

Tools:
  vite             Not found
  rolldown         Not found
  vitest           Not found
  oxfmt            Not found
  oxlint           Not found
  oxlint-tsgolint  Not found
  tsdown           Not found
```

### Used Package Manager

pnpm

### Logs

```shell

```

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/voidzero-dev/vite-plus/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/voidzero-dev/vite-plus/issues) for the same bug.
- [x] Confirm this is a Vite+ issue and not an upstream issue (Vite, Vitest, tsdown, Rolldown, or Oxc).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

### PR DESCRIPTION
**Pull request by naokihaba**
### Linked issue

resolves #828 

### Description

The behavior when specifying an invalid template name (e.g., vite-plus-app) with the vp create command has been improved.

With this update, the CLI now checks the npm registry before executing the package manager. If the template is not found (HTTP 404 error), it will display an error message and terminate the process immediately.

### CODE REVIEW

File: packages/cli/src/utils/package.ts [hunk 1]
```diff
@@ -5,6 +5,25 @@ import path from 'node:path';
...
+ * Returns true if the package exists or if the check could not be performed (network error, timeout).
+ * Returns false only if the registry definitively responds with 404.
+ */
+export async function checkNpmPackageExists(packageName: string): Promise<boolean> {
+  const atIndex = packageName.indexOf('@', 2);
+  const name = atIndex === -1 ? packageName : packageName.slice(0, atIndex);
+  try {
+    const response = await fetch(`https://registry.npmjs.org/${name}`, {
+      method: 'HEAD',
+      signal: AbortSignal.timeout(3000),
```
Comment (naokihaba) [inline packages/cli/src/utils/package.ts]: The CLI may wait silently for dozens of seconds if the npm registry is slow or experiencing an outage. I have decided to implement a timeout using AbortSignal.timeout(3000).
