### PR TITLE
fix(migrate): auto-remove esModuleInterop: false from tsconfig.json

### LINKED ISSUE #1145: `vp migrate` should auto remove `esModuleInterop: false` from tsconfig.json
Avoid `vp lint --type-aware` error. 

```bash
vp lint
VITE+ - The Unified Toolchain for the Web

The plugin "vite-tsconfig-paths" is detected. Vite now supports tsconfig paths resolution natively via the resolve.tsconfigPaths option. You can remove the plugin and set resolve.tsconfigPaths: true in your Vite config instead.

  × typescript(tsconfig-error): Invalid tsconfig
    ╭─[tsconfig.json:9:24]
  8 │     "skipLibCheck": true,
  9 │     "esModuleInterop": false,
    ·                        ─────
 10 │     "allowSyntheticDefaultImports": true,
    ╰────
  help: Option 'esModuleInterop=false' has been removed. Please remove it from your configuration.
        See https://github.com/oxc-project/tsgolint/issues/351 for more information.

Found 0 warnings and 1 error.
Finished in 233ms on 13 files with 213 rules using 16 threads.
```

reproduce repo: https://github.com/fengmk2/bun-vite-template/tree/esModuleInterop-false

### PR DESCRIPTION
**Pull request by fengmk2**
Closes #1145

When `vp migrate` runs, it now scans all tsconfig*.json files and
removes `"esModuleInterop": false` which has been deprecated by
oxlint's tsgolint and causes lint errors with type-aware checking.

### CODE REVIEW

File: packages/cli/src/migration/migrator.ts [hunk 1]
```diff
@@ -643,6 +647,28 @@ function rewritePrettierLintStagedConfigFiles(projectPath: string, report?: Migr
...
+  for (const filePath of files) {
+    if (removeEsModuleInteropFalseFromFile(filePath)) {
+      if (report) {
+        report.removedConfigCount++;
+      }
+      if (!silent) {
+        prompts.log.success(`✔ Removed esModuleInterop: false from ${displayRelative(filePath)}`);
+      }
+      warnMigration(
+        `Removed \`"esModuleInterop": false\` from ${displayRelative(filePath)} — this option has been deprecated and causes oxlint type-aware lint errors. See https://github.com/oxc-project/tsgolint/issues/351`,
```
Comment (fengmk2) [inline packages/cli/src/migration/migrator.ts]: @camc314 Can you help take a look at whether this handling and description are reasonable?

File: rfcs/migration-command.md [hunk 2]
```diff
@@ -605,6 +605,21 @@ When a Prettier configuration file (`.prettierrc*`, `prettier.config.*`, or `"pr
...
+**Currently removed options**:
+
+- `"esModuleInterop": false` — This option has been removed by oxlint's tsgolint. When present, `vp lint --type-aware` fails with: `Option 'esModuleInterop=false' has been removed.`
+
+**Behavior**:
+
+- Only `esModuleInterop: false` is removed — `true` is left alone
+- Uses `jsonc-parser` for JSONC-aware editing that preserves comments and formatting
+- Scans all `tsconfig*.json` variants (e.g., `tsconfig.json`, `tsconfig.app.json`, `tsconfig.node.json`)
+- Runs automatically as part of the config rewrite phase — no user prompt needed
```
Comment (camc314) [inline rfcs/migration-command.md]: Maybe rephrase this?

 - oxlint's tsgolint hasn't remove it, typescript has?

File: packages/cli/src/migration/migrator.ts (hunk 1 above)
Comment (camc314) [reply packages/cli/src/migration/migrator.ts]:
```suggestion
        `Removed \`"esModuleInterop": false\` from ${displayRelative(filePath)} — this option has been deprecated See https://github.com/oxc-project/tsgolint/issues/351, https://github.com/microsoft/TypeScript/issues/62529`,
```

Seems reasonable - probably also worth linking to the typescript issue removing the feature

File: rfcs/migration-command.md (hunk 2 above)
Comment (fengmk2) [reply rfcs/migration-command.md]: `"esModuleInterop": false` — This option has been removed by typescript. When present, `vp lint --type-aware` fails with: `Option 'esModuleInterop=false' has been removed.`

Comment (camc314) [reply rfcs/migration-command.md]: yep sounds good

File: .github/workflows/e2e-test.yml [hunk 3]
```diff
@@ -292,8 +292,8 @@ jobs:
           - name: bun-vite-template
             node-version: 24
             command: |
-              vp run build
-              vp run test
+              vp fmt
+              vp run validate
```
Comment (cpojer) [inline .github/workflows/e2e-test.yml:296]: Why this change?

Comment (fengmk2) [reply .github/workflows/e2e-test.yml:296]: https://github.com/why-reproductions-are-required/bun-vite-template/blob/master/package.json#L18
validate includes complete lint validation. Previously only test was run, but after this fix, lint can also run too.
