### PR TITLE
fix: stop intercepting `vite` as `vp` and synthesize `vpr` in task scripts

### LINKED ISSUE #1176: Pressing Ctrl+C after vp run dev, pnpm run dev, or npm run dev leaves the terminal in a broken state on Windows
### Describe the bug

 - On Windows, after starting the dev server and stopping it with Ctrl+C, the terminal is left in a broken or unusable state.
 - Common symptoms include:
   - terminal input becomes sluggish or freezes
   - Backspace behaves incorrectly and prints ^H 
   - Ctrl+C is echoed as ^C
 - This issue is reproducible with `vp run dev`, `pnpm run dev`, and `npm run dev`.

- The issue does not reproduce with:
   - `bun run dev`
   - `.\node_modules\.bin\vite.CMD`
   - `.\node_modules\.bin\vite.ps1`
   - `C:\Users\Curtion\Desktop\node-v24.14.1-win-x64\npm.cmd run dev`(Native Node.js)
   - `C:\Users\Curtion\Desktop\node-v24.14.1-win-x64\npm.ps1 run dev`(Native Node.js)

https://github.com/user-attachments/assets/275ac35b-f031-45e3-ae7d-29261af21c4a

### Reproduction

https://github.com/Curtion/report-vite-plus-1

### Steps to reproduce

 - Open a terminal on Windows.
 - Go to the project root directory.
 - Run one of the following commands:
   - `vp run dev`
   - `pnpm run dev`
   - `npm run dev`
 - Wait for the dev server to start.
 - Press Ctrl+C once to stop the process.
 - Observe that the terminal enters an abnormal state:
   - input becomes slow or unresponsive
   - Backspace prints ^H
   - Ctrl+C prints ^C

### System Info

```shell
@Curtion ➜ report-vite-plus-1 git(main) vp env current
VITE+ - The Unified Toolchain for the Web

Environment:
  Version  24.14.1
  Source   lts

Tool Paths:
  node  C:\Users\Curtion\.vite-plus\js_runtime\node\24.14.1\node.exe
  npm   C:\Users\Curtion\.vite-plus\js_runtime\node\24.14.1\npm.cmd
  npx   C:\Users\Curtion\.vite-plus\js_runtime\node\24.14.1\npx.cmd
@Curtion ➜ report-vite-plus-1 git(main) vp --version  
VITE+ - The Unified Toolchain for the Web

vp v0.1.14

Local vite-plus:
  vite-plus  Not found

Tools:
  vite             Not found
  rolldown         Not found
  vitest           Not found
  oxfmt            Not found
  oxlint           Not found
  oxlint-tsgolint  Not found
  tsdown           Not found

Environment:
  Package manager  pnpm v10.28.0
  Node.js          v24.14.1
@Curtion ➜ report-vite-plus-1 git(main)
```

### Used Package Manager

pnpm

### Logs

```shell

```

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/voidzero-dev/vite-plus/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/voidzero-dev/vite-plus/issues) for the same bug.
- [x] Confirm this is a Vite+ issue and not an upstream issue (Vite, Vitest, tsdown, Rolldown, or Oxc).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

### PR DESCRIPTION
**Pull request by fengmk2**
## Summary

- **Fix**: `VitePlusCommandHandler` was intercepting both `vp` and `vite` program names in task scripts. This caused `vp run dev` to fail with "Invalid vite task command" when a package.json script used bare `vite` (e.g. `"dev": "vite"`), because `vite` is a separate tool, not a vp alias. Now only `vp` and `vpr` are intercepted; `vite` runs verbatim as an external process.
- **Feat**: `vpr` commands in task scripts (e.g. `"ready": "vpr hello && vpr dev"`) are now expanded to `vp run` and synthesized in-session, avoiding unnecessary process spawns.

## Test plan

- [x] Added snap test `command-run-script-vite-program` covering:
  - bare `vite`, `vite -h`, `vite --version` all run verbatim
  - `vpr hello` synthesized in-session
  - chained `vpr hello-vpr && vpr dev-version` both synthesized
- [x] All 254 global snap tests pass
- [x] All 22 Rust unit tests pass
- [x] Verified on real reproduction project (`vp run dev` starts Vite dev server)

Closes #1176

### CODE REVIEW

File: packages/cli/binding/src/cli.rs [hunk 1]
```diff
@@ -551,16 +551,12 @@ impl CommandHandler for VitePlusCommandHandler {
...
     ) -> anyhow::Result<HandledCommand> {
-        // Intercept both "vp" and "vite" commands in task scripts.
-        // "vp" is the conventional alias used in vite-plus task configs.
-        // "vite" must also be intercepted so that `vite test`, `vite build`, etc.
-        // in task scripts are synthesized in-session rather than spawning a new CLI process.
+        // Intercept "vp" commands in task scripts so that `vp test`, `vp build`, etc.
+        // are synthesized in-session rather than spawning a new CLI process.
         let program = command.program.as_str();
-        if program != "vp" && program != "vite" {
+        if program != "vp" {
```
Comment (fengmk2) [inline packages/cli/binding/src/cli.rs]: should handle vpr as `vp run` too.
