### PR TITLE
fix(cli): override rolldown panic hook with vite-plus branding

### LINKED ISSUE #1285: Any panics in viteplus has the panic message generated by Rolldown
When a panic happens, it has a message like below:
```
error: Lint or type issues found
Rolldown panicked. This is a bug in Rolldown, not your code.

thread '<unnamed>' (8114667) panicked at library/std/src/io/stdio.rs:1165:9:
failed printing to stdout: Resource temporarily unavailable (os error 35)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Please report this issue at: https://github.com/rolldown/rolldown/issues/new?template=panic_report.yml
× eslint-plugin-react(react-in-jsx-scope): `React` must be in scope when using JSX.
    ╭─[src/components/changelog/SignUpForm.tsx:9:6]
  8 │   return (
  9 │     <form className="relative isolate mt-8 flex items-center pr-1">
    ·      ────
 10 │       <label htmlFor={id} className="sr-only">
    ╰────
  help: When using JSX, `<a />` expands to `React.createElement("a")`. Therefore the `React` variable must be in scope.

  × eslint-plugin-react(react-in-jsx-scope): `React` must be in scope when using JSX.
    ╭─[src/components/changelog/SignUpForm.tsx:10:8]
  9 │     <form className="relative isolate mt-8 flex items-center pr-1">
 10 │       <label htmlFor={id} className="sr-only">
    ·        ─────
 11 │         Email address
    ╰────
  help: When using JSX, `<a />` expands to `React.createElement("a")`. Therefore the `React` variable must be in scope.

```
(Reported at https://github.com/rolldown/rolldown/issues/8906)

This is confusing because the panic is not caused by Rolldown. I guess this panic hook in Rolldown is included in the build.
https://github.com/rolldown/rolldown/blob/37405e7f8b07ad686c0940f14aa347a0eb2ccefd/crates/rolldown_binding/src/lib.rs#L109-L116

### PR DESCRIPTION
**Pull request by fengmk2**
Since rolldown_binding is bundled into the same NAPI binary, its
module_init panic hook catches all panics and misleadingly shows
"Rolldown panicked" with a link to rolldown's issue tracker.

Replace it at the start of run() with a vite-plus specific hook that
correctly attributes panics and links to the vite-plus bug report.

Closes #1285

### CODE REVIEW

File: packages/cli/binding/src/lib.rs [hunk 1]
```diff
@@ -123,13 +123,35 @@ fn format_error_message(error: &(dyn StdError + 'static)) -> String {
...
+/// Install a Vite+ panic hook so panics are correctly attributed to Vite+.
+///
+/// Discards any previously set hook (e.g. rolldown's) via double `take_hook`:
+/// first call removes the current hook, second captures the restored default.
+/// Safe to call regardless of whether a custom hook was installed.
+#[allow(clippy::disallowed_macros)]
+fn setup_panic_hook() {
+    static ONCE: std::sync::Once = std::sync::Once::new();
+    ONCE.call_once(|| {
+        let _ = std::panic::take_hook();
```
Comment (fengmk2) [inline packages/cli/binding/src/lib.rs:135]: https://github.com/voidzero-dev/vite-plus/issues/1285#issuecomment-4183685852 It would be better if there was a way to disable rolldown's panic hook

File: packages/cli/binding/src/lib.rs [hunk 2]
```diff
@@ -123,13 +123,35 @@ fn format_error_message(error: &(dyn StdError + 'static)) -> String {
...
+}
+
 /// Main entry point for the CLI, called from JavaScript.
 ///
 /// This is an async function that spawns a new thread for the non-Send async code
 /// from vite_task, while allowing the NAPI async context to continue running
 /// and process JavaScript callbacks (via ThreadsafeFunction).
 #[napi]
 pub async fn run(options: CliOptions) -> Result<i32> {
+    setup_panic_hook();
```
Comment (wan9chi) [inline packages/cli/binding/src/lib.rs:154]: Is rolldown's panic hook setup before this?

Comment (fengmk2) [reply packages/cli/binding/src/lib.rs:154]: https://github.com/rolldown/rolldown/blob/37405e7f8b07ad686c0940f14aa347a0eb2ccefd/crates/rolldown_binding/src/lib.rs#L109-L116 yes
