### PR TITLE
fix(cli): suppress Vite+ header in non-TTY and git hook contexts

### LINKED ISSUE #1396: vp hangs when spawned by lefthook (opens /dev/tty)
### Describe the bug

`vp` commands hang indefinitely when spawned as child processes by [lefthook](https://github.com/evilmartians/lefthook) git hooks. The same commands complete in ~1 second when run directly in a terminal.

```bash
# Works fine (~1s):
vp run typecheck

# Hangs indefinitely:
git add lefthook.yml && npx lefthook run pre-commit
```

Both `vp run <script>` and `vp test` are affected.

#### Root cause

`lsof` on the hanging `vp` process shows it opens `/dev/tty` directly (fd 9), bypassing stdin:

```
COMMAND   PID    USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
vp      11794 spalger    0u   CHR   16,0      0t0  895 /dev/ttys000
vp      11794 spalger    1u   CHR   16,0      0t0  895 /dev/ttys000
vp      11794 spalger    2u   CHR   16,0      0t0  895 /dev/ttys000
vp      11794 spalger    9u   CHR    2,0     0t26  335 /dev/tty
```

Lefthook allocates pseudo-TTYs for child processes. When `vp` opens `/dev/tty` and reads from it, it blocks because there's no input on the pseudo-TTY.

This is partly a lefthook issue too — lefthook gives non-interactive child processes a controlling terminal even though it already treats them as non-interactive (null stdin per [evilmartians/lefthook#732](https://github.com/evilmartians/lefthook/pull/732)). But `vp` could also handle the case where `/dev/tty` isn't truly interactive more gracefully, rather than blocking indefinitely.

#### Workaround

Redirect stdin from `/dev/null`:

```yaml
pre-commit:
  commands:
    typecheck:
      run: vp run typecheck </dev/null
    test:
      run: vp test </dev/null
```

### Reproduction

Can't manage to run `curl -fsSL https://vite.plus | bash` in stackblitz sandboxes...

### Steps to reproduce

- Install lefthook npm install --save-dev lefthook
- Write lefthook.yml file

`lefthook.yml`:
```yaml
pre-commit:
  commands:
    typecheck:
      run: vp run typecheck
```

- Run `npx lefthook run pre-commit`

### System Info

```shell
VITE+ - The Unified Toolchain for the Web

Environment:
  Version  24.14.1
  Source   lts

Tool Paths:
  node  /Users/spalger/.vite-plus/js_runtime/node/24.14.1/bin/node
  npm   /Users/spalger/.vite-plus/js_runtime/node/24.14.1/bin/npm
  npx   /Users/spalger/.vite-plus/js_runtime/node/24.14.1/bin/npx

vp v0.1.16

Local vite-plus:
  vite-plus  Not found

Tools:
  vite             Not found
  rolldown         Not found
  vitest           Not found
  oxfmt            Not found
  oxlint           Not found
  oxlint-tsgolint  Not found
  tsdown           Not found

Environment:
  Package manager  pnpm v10.33.0
  Node.js          v24.14.1
```

### Used Package Manager

pnpm

### Logs

```shell

```

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/voidzero-dev/vite-plus/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/voidzero-dev/vite-plus/issues) for the same bug.
- [x] Confirm this is a Vite+ issue and not an upstream issue (Vite, Vitest, tsdown, Rolldown, or Oxc).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

### PR DESCRIPTION
**Pull request by fengmk2**
The banner was printing from every `vp` invocation, cluttering captured
output (lefthook/husky, `execSync`, CI pipes, pagers) and the git commit
flow when a shell pre-commit hook runs `vp check --fix` — in the hook
the colour detection is unreliable, so the banner also rendered in a
degraded style.

Banner emission now gates on two signals at every call site:

- `stdout.is_terminal()` — catches piped/redirected contexts.
- `GIT_INDEX_FILE` env var — catches direct shell hooks that inherit
  the terminal for stdout. Git sets this for pre-commit, commit-msg,
  and prepare-commit-msg, which is where `vp check --fix` typically
  runs.

Centralised behind `vite_shared::header::print_header()` on the Rust
side and a new `printHeader()` helper in `packages/cli/src/utils/
terminal.ts` on the Node CLI side. The interactive `prompts.intro()` in
`vp create` and the interactive top-level command picker are left
alone — they only run when genuinely interactive.

Snap fixtures regenerated to reflect the removed banner lines.

---

> [!NOTE]
> **Medium Risk**
> Primarily changes CLI stdout formatting, which may affect scripts/tests that assert exact output; the gating relies on TTY detection and `GIT_INDEX_FILE`, so edge environments could suppress (or unexpectedly show) the banner.
> 
> **Overview**
> Prevents the Vite+ banner from being emitted in non-interactive contexts by introducing `vite_shared::header::should_print_header()` (TTY + `GIT_INDEX_FILE` gating) and a centralized `print_header()` helper.
> 
> Updates the Rust global CLI to call `print_header()` (and to omit the header in clap help templates unless `should_print_header()` passes), and updates the Node CLI to use a new `printHeader()` helper that delegates the same gating via a newly-exposed N-API binding `shouldPrintVitePlusHeader()`.
> 
> Regenerates CLI snapshot fixtures to reflect the banner being absent in captured/help/test outputs where it’s now suppressed.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 918c3db340b99b10f8443eecefe6d729accdd464. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

**Comment by fengmk2** [comment]
* **#1439** <a href="https://app.graphite.com/github/pr/voidzero-dev/vite-plus/1439?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/voidzero-dev/vite-plus/1439?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`
<hr />

## How to use the Graphite Merge Queue

Add the label <kbd>auto-merge</kbd> to this PR to add it to the merge queue.

You must have a Graphite account in order to use the merge queue. Sign up using [this link](https://app.graphite.com/invite/github/voidzero-dev?ref=merge-queue-instructions-in-stack-comment&prId=1439).

<h2></h2>
<sub>

An organization admin has enabled the [Graphite Merge Queue](https://graphite.dev/docs/graphite-merge-queue) in this repository.

</sub>

<sub>

Please do not merge from GitHub as this will restart CI on PRs being processed by the merge queue.

</sub>

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by fengmk2** [comment]
@cursor review

File: packages/cli/src/utils/terminal.ts [hunk 1]
```diff
@@ -1,10 +1,33 @@
...
+ * Emit the Vite+ banner (header line + trailing blank line) to stdout.
+ *
+ * Silent when:
+ * - stdout is piped or redirected (lefthook/husky, `execSync`, CI, pagers) —
+ *   the banner's ANSI styling renders inconsistently there.
+ * - a git commit-flow hook is running. Direct shell hooks inherit the
+ *   terminal for stdout, so the TTY check alone doesn't catch them; git
+ *   sets `GIT_INDEX_FILE` for pre-commit / commit-msg / prepare-commit-msg.
+ */
+export function printHeader() {
```
Comment (fengmk2) [inline packages/cli/src/utils/terminal.ts:15]: This logic should be supported by binding as well, without needing to repeat it on the JS side.

**Review by cpojer — APPROVED** [review]

**Comment by fengmk2** [comment]
@cursor review
