### PR TITLE
fix(cli): warn when object-form manualChunks is detected

### LINKED ISSUE #900: vp migrate: Rolldown requires function-form manualChunks (object form causes build failure)
## Describe the bug

After `vp migrate`, projects that use object-form `manualChunks` in their Vite config fail to build because Rolldown does not support the object form.

```
Warning: Invalid output options (1 issue found)
- For the "manualChunks". Invalid type: Expected Function but received Object.

TypeError: manualChunks is not a function
```

`vp migrate` should convert object-form `manualChunks` to function form, or at minimum warn about this incompatibility.

### Before (works with Rollup, fails with Rolldown)

```js
manualChunks: {
  'react': ['react', 'react-dom'],
}
```

### After (works with Rolldown)

```js
manualChunks(id) {
  if (id.includes('node_modules/react/') || id.includes('node_modules/react-dom/')) {
    return 'react';
  }
}
```

## Reproduction

1. Have a Vite project with object-form `manualChunks` in `vite.config.js`
2. Run `vp migrate`
3. Run `vp build`

## System Info

```
vp v0.1.11

Local vite-plus:
  vite-plus  v0.1.11

Tools:
  vite             v8.0.0
  rolldown         v1.0.0-rc.9
  vitest           v4.1.0
  oxfmt            v0.40.0
  oxlint           v1.55.0
  oxlint-tsgolint  v0.16.0
  tsdown           v0.21.2

Environment:
  Version  24.14.0
  Source   lts
```

## Logs

```
Warning: Invalid output options (1 issue found)
- For the "manualChunks". Invalid type: Expected Function but received Object.

TypeError: manualChunks is not a function
    at name (file:///path/to/node_modules/@voidzero-dev/vite-plus-core/dist/rolldown/shared/rolldown-build-CYoDea9V.mjs:3102:10)
```

### PR DESCRIPTION
**Pull request by kazupon**
resolve #900

### CODE REVIEW

File: packages/cli/src/migration/bin.ts [hunk 1]
```diff
@@ -539,6 +539,17 @@ function showMigrationSummary(options: {
   }
 }
 
+async function checkRolldownCompatibility(rootDir: string, report: MigrationReport): Promise<void> {
+  try {
+    const { resolveConfig } = await import('../index.js');
+    const { checkManualChunksCompat } = await import('./compat.js');
+    const config = await resolveConfig({ root: rootDir, logLevel: 'silent' }, 'build');
```
Comment (kazupon) [inline packages/cli/src/migration/bin.ts]: Hmm, `logLevel: 'silent'` not propagated to Rolldown during config bundling

When calling `resolveConfig({ logLevel: 'silent' })`, the `logLevel` is passed to `loadConfigFromFile` but is **not forwarded** to `bundleConfigFile` → `rolldown()`. This means Rolldown still prints `UNRESOLVED_IMPORT` warnings to stderr even when silent mode is requested, in the migration.

Comment (fengmk2) [reply packages/cli/src/migration/bin.ts]: Should we create an issue for rolldown as a follow-up? This won't block our current fix here.

Comment (kazupon) [reply packages/cli/src/migration/bin.ts]: I've open it as issue at Vite repo
https://github.com/vitejs/vite/issues/21971

Comment (kazupon) [reply packages/cli/src/migration/bin.ts]: I'm currently finding other solutions besides `resolveConfig`.

Comment (kazupon) [reply packages/cli/src/migration/bin.ts]: I could keep to use `resolveConfig`.
https://github.com/voidzero-dev/vite-plus/pull/1046/changes/908b16b41441740100057273d5f3d55a22e559fc

File: packages/cli/src/migration/bin.ts [hunk 2]
```diff
@@ -540,6 +540,22 @@ function showMigrationSummary(options: {
...
 }
 
+async function checkRolldownCompatibility(rootDir: string, report: MigrationReport): Promise<void> {
+  try {
+    const { resolveConfig } = await import('../index.js');
+    const { checkManualChunksCompat } = await import('./compat.js');
+    // Use 'runner' configLoader to avoid Rolldown bundling the config file,
+    // which prints UNRESOLVED_IMPORT warnings that cannot be suppressed via logLevel.
+    const config = await resolveConfig(
+      { root: rootDir, logLevel: 'silent', configLoader: 'runner' },
```
[the remark this answers is not in the document]
Comment (kazupon) [reply packages/cli/src/migration/bin.ts:550]: I think that vite cjs configs are a very rare case in the Vite 8.

Falling back to `'bundle'` would re-introduce the `UNRESOLVED_IMPORT` warnings that are irrelevant to migration (see vitejs/vite#21971).

Even if the check is skipped for cjs configs, Rolldown will still report a clear error at build time when it encounters object-form `manualChunks`, so users won't miss it.
