### PR TITLE
fix(migrate): warn on uncoercible husky version instead of false positive

### LINKED ISSUE #1114: vp migrate false-positive husky version check when version is a dist-tag or non-semver string ("latest", "next", etc.)
### Describe the bug

vp migrate reports "Detected husky <9.0.0 — please upgrade to husky v9+ first, then re-run migration." even when husky v9 is installed. The check reads the version string from package.json devDependencies and uses semver.coerce() on it. When the version is "latest", semver.coerce("latest") returns null, which falls back to "0.0.0" and incorrectly satisfies < 9.0.0.

### Reproduction

https://github.com/mildlyfunctional/vp-migrate-repro

### Steps to reproduce

Steps to reproduce:
1. Clone the reproduction repo
2. Run vp migrate
3. See: Detected husky <9.0.0 — please upgrade to husky v9+ first, then re-run migration.

### System Info

```shell
Environment:
  Version  24.14.0
  Source   lts

Tool Paths:
  node  /Users/mrwokkel/.vite-plus/js_runtime/node/24.14.0/bin/node
  npm   /Users/mrwokkel/.vite-plus/js_runtime/node/24.14.0/bin/npm
  npx   /Users/mrwokkel/.vite-plus/js_runtime/node/24.14.0/bin/npx


vp v0.1.13

Local vite-plus:
  vite-plus  Not found

Tools:
  vite             Not found
  rolldown         Not found
  vitest           Not found
  oxfmt            Not found
  oxlint           Not found
  oxlint-tsgolint  Not found
  tsdown           Not found

Environment:
  Package manager  pnpm v10.32.1
  Node.js          v24.14.0
```

### Used Package Manager

npm

### Logs

```shell

```

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/voidzero-dev/vite-plus/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/voidzero-dev/vite-plus/issues) for the same bug.
- [x] Confirm this is a Vite+ issue and not an upstream issue (Vite, Vitest, tsdown, Rolldown, or Oxc).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

### PR DESCRIPTION
**Pull request by jong-kyung**
## Summary

- Fix false positive "husky <9.0.0" warning in `vp migrate` when husky version is a dist-tag (`"latest"`, `"next"`) or other non-semver string
- When `semver.coerce()` returns `null`, warn the user to specify a semver-compatible version instead of silently falling back to `'0.0.0'`
- Change `checkUnsupportedHuskyVersion` return type from `boolean` to `string | null` to co-locate message logic with version checking

Closes #1114

### CODE REVIEW

File: packages/cli/src/migration/migrator.ts [hunk 1]
```diff
@@ -1510,18 +1510,25 @@ function rewriteAllImports(projectPath: string, silent = false, report?: Migrati
...
-): boolean {
+): string | null {
   const huskyVersion = deps?.husky ?? prodDeps?.husky;
   if (!huskyVersion) {
-    return false;
+    return null;
   }
-  return semver.satisfies(semver.coerce(huskyVersion) ?? '0.0.0', '<9.0.0');
+  const coerced = semver.coerce(huskyVersion);
+  if (coerced == null) {
```
Comment (fengmk2) [inline packages/cli/src/migration/migrator.ts:1528]: Under this condition, should we try to read the version of husky installed in node_modules? It's very likely that the user has already executed npm install in the current project, and in this case, we can read the actual version.

Comment (jong-kyung) [reply packages/cli/src/migration/migrator.ts:1528]: > Under this condition, should we try to read the version of husky installed in node_modules? It's very likely that the user has already executed npm install in the current project, and in this case, we can read the actual version.

Good point! Will use the `detectPackageMetadata` function from `package.ts` to read the installed version from node_modules as a fallback when semver.coerce fails, keeping the current warning only when node_modules isn't available

**Review by fengmk2 — APPROVED** [review]
